(cl:in-package iarc_arena_simulator-msg)
(cl:export '(HEADER-VAL
          HEADER
          SEQ-VAL
          SEQ
          TMS-VAL
          TMS
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          AX-VAL
          AX
          AY-VAL
          AY
          AZ-VAL
          AZ
          ROBOT_ID-VAL
          ROBOT_ID
          ROBOT_CMD-VAL
          ROBOT_CMD
))