"""autogenerated by genpy from iarc_arena_simulator/IARCTask.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class IARCTask(genpy.Message):
  _md5sum = "05a68d9a9434319b9367e7aa299c52f7"
  _type = "iarc_arena_simulator/IARCTask"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# task
Header header
uint8 task_type
uint32 task_seq
float32 task_value
uint32 time_start
uint32 time_end
uint32 robot_id
uint32 robot_cmd
geometry_msgs/Pose final_pose
geometry_msgs/Pose final_bound


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

"""
  __slots__ = ['header','task_type','task_seq','task_value','time_start','time_end','robot_id','robot_cmd','final_pose','final_bound']
  _slot_types = ['std_msgs/Header','uint8','uint32','float32','uint32','uint32','uint32','uint32','geometry_msgs/Pose','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,task_type,task_seq,task_value,time_start,time_end,robot_id,robot_cmd,final_pose,final_bound

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IARCTask, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.task_type is None:
        self.task_type = 0
      if self.task_seq is None:
        self.task_seq = 0
      if self.task_value is None:
        self.task_value = 0.
      if self.time_start is None:
        self.time_start = 0
      if self.time_end is None:
        self.time_end = 0
      if self.robot_id is None:
        self.robot_id = 0
      if self.robot_cmd is None:
        self.robot_cmd = 0
      if self.final_pose is None:
        self.final_pose = geometry_msgs.msg.Pose()
      if self.final_bound is None:
        self.final_bound = geometry_msgs.msg.Pose()
    else:
      self.header = std_msgs.msg.Header()
      self.task_type = 0
      self.task_seq = 0
      self.task_value = 0.
      self.time_start = 0
      self.time_end = 0
      self.robot_id = 0
      self.robot_cmd = 0
      self.final_pose = geometry_msgs.msg.Pose()
      self.final_bound = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BIf4I14d.pack(_x.task_type, _x.task_seq, _x.task_value, _x.time_start, _x.time_end, _x.robot_id, _x.robot_cmd, _x.final_pose.position.x, _x.final_pose.position.y, _x.final_pose.position.z, _x.final_pose.orientation.x, _x.final_pose.orientation.y, _x.final_pose.orientation.z, _x.final_pose.orientation.w, _x.final_bound.position.x, _x.final_bound.position.y, _x.final_bound.position.z, _x.final_bound.orientation.x, _x.final_bound.orientation.y, _x.final_bound.orientation.z, _x.final_bound.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.final_pose is None:
        self.final_pose = geometry_msgs.msg.Pose()
      if self.final_bound is None:
        self.final_bound = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 137
      (_x.task_type, _x.task_seq, _x.task_value, _x.time_start, _x.time_end, _x.robot_id, _x.robot_cmd, _x.final_pose.position.x, _x.final_pose.position.y, _x.final_pose.position.z, _x.final_pose.orientation.x, _x.final_pose.orientation.y, _x.final_pose.orientation.z, _x.final_pose.orientation.w, _x.final_bound.position.x, _x.final_bound.position.y, _x.final_bound.position.z, _x.final_bound.orientation.x, _x.final_bound.orientation.y, _x.final_bound.orientation.z, _x.final_bound.orientation.w,) = _struct_BIf4I14d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BIf4I14d.pack(_x.task_type, _x.task_seq, _x.task_value, _x.time_start, _x.time_end, _x.robot_id, _x.robot_cmd, _x.final_pose.position.x, _x.final_pose.position.y, _x.final_pose.position.z, _x.final_pose.orientation.x, _x.final_pose.orientation.y, _x.final_pose.orientation.z, _x.final_pose.orientation.w, _x.final_bound.position.x, _x.final_bound.position.y, _x.final_bound.position.z, _x.final_bound.orientation.x, _x.final_bound.orientation.y, _x.final_bound.orientation.z, _x.final_bound.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.final_pose is None:
        self.final_pose = geometry_msgs.msg.Pose()
      if self.final_bound is None:
        self.final_bound = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 137
      (_x.task_type, _x.task_seq, _x.task_value, _x.time_start, _x.time_end, _x.robot_id, _x.robot_cmd, _x.final_pose.position.x, _x.final_pose.position.y, _x.final_pose.position.z, _x.final_pose.orientation.x, _x.final_pose.orientation.y, _x.final_pose.orientation.z, _x.final_pose.orientation.w, _x.final_bound.position.x, _x.final_bound.position.y, _x.final_bound.position.z, _x.final_bound.orientation.x, _x.final_bound.orientation.y, _x.final_bound.orientation.z, _x.final_bound.orientation.w,) = _struct_BIf4I14d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_BIf4I14d = struct.Struct("<BIf4I14d")
