// Generated by gencpp from file iarc_arena_simulator/IARCObstacles.msg
// DO NOT EDIT!


#ifndef IARC_ARENA_SIMULATOR_MESSAGE_IARCOBSTACLES_H
#define IARC_ARENA_SIMULATOR_MESSAGE_IARCOBSTACLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseStamped.h>

namespace iarc_arena_simulator
{
template <class ContainerAllocator>
struct IARCObstacles_
{
  typedef IARCObstacles_<ContainerAllocator> Type;

  IARCObstacles_()
    : header()
    , obstacles()  {
    }
  IARCObstacles_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , obstacles(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  _obstacles_type;
  _obstacles_type obstacles;




  typedef boost::shared_ptr< ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator> const> ConstPtr;

}; // struct IARCObstacles_

typedef ::iarc_arena_simulator::IARCObstacles_<std::allocator<void> > IARCObstacles;

typedef boost::shared_ptr< ::iarc_arena_simulator::IARCObstacles > IARCObstaclesPtr;
typedef boost::shared_ptr< ::iarc_arena_simulator::IARCObstacles const> IARCObstaclesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iarc_arena_simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'iarc_arena_simulator': ['/home/exbot/workspace/hehualin_ws/distribute/src/iarc_arena_simulator/msg'], 'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5cde8b253f406554c88bf2111d36a33e";
  }

  static const char* value(const ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5cde8b253f406554ULL;
  static const uint64_t static_value2 = 0xc88bf2111d36a33eULL;
};

template<class ContainerAllocator>
struct DataType< ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iarc_arena_simulator/IARCObstacles";
  }

  static const char* value(const ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# obstacles\n\
Header header\n\
geometry_msgs/PoseStamped[] obstacles\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct IARCObstacles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iarc_arena_simulator::IARCObstacles_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IARC_ARENA_SIMULATOR_MESSAGE_IARCOBSTACLES_H
