// Generated by gencpp from file iarc_arena_simulator/IARCWaypointsList.msg
// DO NOT EDIT!


#ifndef IARC_ARENA_SIMULATOR_MESSAGE_IARCWAYPOINTSLIST_H
#define IARC_ARENA_SIMULATOR_MESSAGE_IARCWAYPOINTSLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <iarc_arena_simulator/IARCWaypoint.h>

namespace iarc_arena_simulator
{
template <class ContainerAllocator>
struct IARCWaypointsList_
{
  typedef IARCWaypointsList_<ContainerAllocator> Type;

  IARCWaypointsList_()
    : header()
    , seq(0)
    , list()  {
    }
  IARCWaypointsList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , seq(0)
    , list(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _seq_type;
  _seq_type seq;

   typedef std::vector< ::iarc_arena_simulator::IARCWaypoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::iarc_arena_simulator::IARCWaypoint_<ContainerAllocator> >::other >  _list_type;
  _list_type list;




  typedef boost::shared_ptr< ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator> const> ConstPtr;

}; // struct IARCWaypointsList_

typedef ::iarc_arena_simulator::IARCWaypointsList_<std::allocator<void> > IARCWaypointsList;

typedef boost::shared_ptr< ::iarc_arena_simulator::IARCWaypointsList > IARCWaypointsListPtr;
typedef boost::shared_ptr< ::iarc_arena_simulator::IARCWaypointsList const> IARCWaypointsListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iarc_arena_simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'iarc_arena_simulator': ['/home/exbot/workspace/hehualin_ws/distribute/src/iarc_arena_simulator/msg'], 'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d3da800b642bca88f56e03fa772af9a";
  }

  static const char* value(const ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d3da800b642bca8ULL;
  static const uint64_t static_value2 = 0x8f56e03fa772af9aULL;
};

template<class ContainerAllocator>
struct DataType< ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iarc_arena_simulator/IARCWaypointsList";
  }

  static const char* value(const ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# waypoint\n\
Header header\n\
uint32 seq\n\
IARCWaypoint[] list\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: iarc_arena_simulator/IARCWaypoint\n\
# waypoint\n\
Header header\n\
uint32 seq\n\
uint32 tms\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 vx\n\
float32 vy\n\
float32 vz\n\
float32 ax\n\
float32 ay\n\
float32 az\n\
uint32 robot_id\n\
uint32 robot_cmd\n\
";
  }

  static const char* value(const ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.seq);
      stream.next(m.list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct IARCWaypointsList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iarc_arena_simulator::IARCWaypointsList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seq);
    s << indent << "list[]" << std::endl;
    for (size_t i = 0; i < v.list.size(); ++i)
    {
      s << indent << "  list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::iarc_arena_simulator::IARCWaypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IARC_ARENA_SIMULATOR_MESSAGE_IARCWAYPOINTSLIST_H
