// Generated by gencpp from file iarc_arena_simulator/IARCTask.msg
// DO NOT EDIT!


#ifndef IARC_ARENA_SIMULATOR_MESSAGE_IARCTASK_H
#define IARC_ARENA_SIMULATOR_MESSAGE_IARCTASK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace iarc_arena_simulator
{
template <class ContainerAllocator>
struct IARCTask_
{
  typedef IARCTask_<ContainerAllocator> Type;

  IARCTask_()
    : header()
    , task_type(0)
    , task_seq(0)
    , task_value(0.0)
    , time_start(0)
    , time_end(0)
    , robot_id(0)
    , robot_cmd(0)
    , final_pose()
    , final_bound()  {
    }
  IARCTask_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , task_type(0)
    , task_seq(0)
    , task_value(0.0)
    , time_start(0)
    , time_end(0)
    , robot_id(0)
    , robot_cmd(0)
    , final_pose(_alloc)
    , final_bound(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _task_type_type;
  _task_type_type task_type;

   typedef uint32_t _task_seq_type;
  _task_seq_type task_seq;

   typedef float _task_value_type;
  _task_value_type task_value;

   typedef uint32_t _time_start_type;
  _time_start_type time_start;

   typedef uint32_t _time_end_type;
  _time_end_type time_end;

   typedef uint32_t _robot_id_type;
  _robot_id_type robot_id;

   typedef uint32_t _robot_cmd_type;
  _robot_cmd_type robot_cmd;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _final_pose_type;
  _final_pose_type final_pose;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _final_bound_type;
  _final_bound_type final_bound;




  typedef boost::shared_ptr< ::iarc_arena_simulator::IARCTask_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iarc_arena_simulator::IARCTask_<ContainerAllocator> const> ConstPtr;

}; // struct IARCTask_

typedef ::iarc_arena_simulator::IARCTask_<std::allocator<void> > IARCTask;

typedef boost::shared_ptr< ::iarc_arena_simulator::IARCTask > IARCTaskPtr;
typedef boost::shared_ptr< ::iarc_arena_simulator::IARCTask const> IARCTaskConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iarc_arena_simulator::IARCTask_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iarc_arena_simulator::IARCTask_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iarc_arena_simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'iarc_arena_simulator': ['/home/exbot/workspace/hehualin_ws/distribute/src/iarc_arena_simulator/msg'], 'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iarc_arena_simulator::IARCTask_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_arena_simulator::IARCTask_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iarc_arena_simulator::IARCTask_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iarc_arena_simulator::IARCTask_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_arena_simulator::IARCTask_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_arena_simulator::IARCTask_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iarc_arena_simulator::IARCTask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05a68d9a9434319b9367e7aa299c52f7";
  }

  static const char* value(const ::iarc_arena_simulator::IARCTask_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05a68d9a9434319bULL;
  static const uint64_t static_value2 = 0x9367e7aa299c52f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::iarc_arena_simulator::IARCTask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iarc_arena_simulator/IARCTask";
  }

  static const char* value(const ::iarc_arena_simulator::IARCTask_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iarc_arena_simulator::IARCTask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# task\n\
Header header\n\
uint8 task_type\n\
uint32 task_seq\n\
float32 task_value\n\
uint32 time_start\n\
uint32 time_end\n\
uint32 robot_id\n\
uint32 robot_cmd\n\
geometry_msgs/Pose final_pose\n\
geometry_msgs/Pose final_bound\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::iarc_arena_simulator::IARCTask_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iarc_arena_simulator::IARCTask_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.task_type);
      stream.next(m.task_seq);
      stream.next(m.task_value);
      stream.next(m.time_start);
      stream.next(m.time_end);
      stream.next(m.robot_id);
      stream.next(m.robot_cmd);
      stream.next(m.final_pose);
      stream.next(m.final_bound);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct IARCTask_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iarc_arena_simulator::IARCTask_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iarc_arena_simulator::IARCTask_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "task_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.task_type);
    s << indent << "task_seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.task_seq);
    s << indent << "task_value: ";
    Printer<float>::stream(s, indent + "  ", v.task_value);
    s << indent << "time_start: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time_start);
    s << indent << "time_end: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.time_end);
    s << indent << "robot_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.robot_id);
    s << indent << "robot_cmd: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.robot_cmd);
    s << indent << "final_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.final_pose);
    s << indent << "final_bound: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.final_bound);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IARC_ARENA_SIMULATOR_MESSAGE_IARCTASK_H
