// Generated by gencpp from file iarc_arena_simulator/IARCCommand.msg
// DO NOT EDIT!


#ifndef IARC_ARENA_SIMULATOR_MESSAGE_IARCCOMMAND_H
#define IARC_ARENA_SIMULATOR_MESSAGE_IARCCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace iarc_arena_simulator
{
template <class ContainerAllocator>
struct IARCCommand_
{
  typedef IARCCommand_<ContainerAllocator> Type;

  IARCCommand_()
    : header()
    , command_kind(0)
    , robot_id(0)  {
    }
  IARCCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , command_kind(0)
    , robot_id(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _command_kind_type;
  _command_kind_type command_kind;

   typedef int32_t _robot_id_type;
  _robot_id_type robot_id;




  typedef boost::shared_ptr< ::iarc_arena_simulator::IARCCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iarc_arena_simulator::IARCCommand_<ContainerAllocator> const> ConstPtr;

}; // struct IARCCommand_

typedef ::iarc_arena_simulator::IARCCommand_<std::allocator<void> > IARCCommand;

typedef boost::shared_ptr< ::iarc_arena_simulator::IARCCommand > IARCCommandPtr;
typedef boost::shared_ptr< ::iarc_arena_simulator::IARCCommand const> IARCCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iarc_arena_simulator::IARCCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iarc_arena_simulator::IARCCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace iarc_arena_simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'iarc_arena_simulator': ['/home/exbot/workspace/hehualin_ws/distribute/src/iarc_arena_simulator/msg'], 'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::iarc_arena_simulator::IARCCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iarc_arena_simulator::IARCCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iarc_arena_simulator::IARCCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iarc_arena_simulator::IARCCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_arena_simulator::IARCCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iarc_arena_simulator::IARCCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iarc_arena_simulator::IARCCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c609693fd9ce982d29367b2eed37c0b";
  }

  static const char* value(const ::iarc_arena_simulator::IARCCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c609693fd9ce982ULL;
  static const uint64_t static_value2 = 0xd29367b2eed37c0bULL;
};

template<class ContainerAllocator>
struct DataType< ::iarc_arena_simulator::IARCCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iarc_arena_simulator/IARCCommand";
  }

  static const char* value(const ::iarc_arena_simulator::IARCCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iarc_arena_simulator::IARCCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# obstacles\n\
Header header\n\
int32 command_kind\n\
int32 robot_id\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::iarc_arena_simulator::IARCCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iarc_arena_simulator::IARCCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.command_kind);
      stream.next(m.robot_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct IARCCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iarc_arena_simulator::IARCCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iarc_arena_simulator::IARCCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "command_kind: ";
    Printer<int32_t>::stream(s, indent + "  ", v.command_kind);
    s << indent << "robot_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IARC_ARENA_SIMULATOR_MESSAGE_IARCCOMMAND_H
